config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "movies#index"
  post 'votes', to: 'votes#create', as: :votes
  delete 'votes', to: 'votes#destroy', as: :vote
  get 'movies/new', as: :new_movie
  post 'movies', to: 'movies#create'
  get 'movies', to: 'movies#index'
  post 'sessions/create', as: :sign_in
  delete 'sessions/destroy', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  # makes Current.user accessible in view files.
  attribute :user
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :votes

  attribute :count_vote_up, :integer, default: 0
  attribute :count_vote_down, :integer, default: 0

  validates :link, presence: true
  validates :count_vote_up, :comparison => { greater_than_or_equal_to: 0 }
  validates :count_vote_down, :comparison => { greater_than_or_equal_to: 0 }

  def update_vote_count
    # This method should be divided into two methods
    # update_vote_up_count
    # update_vote_down_count
    # and use plus, minus operator to update the count, no necesary to make query to database
    self.count_vote_up = votes.where(value: 1).count
    self.count_vote_down = votes.where(value: -1).count
    save
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :votes

  validates :username, presence: true, uniqueness: true, length: { minimum: 5, maximum: 50 }, format: { with: /\A[a-zA-Z0-9]+\Z/,
                                                                                                        message: "only allows letters" }

  validates :password, presence: true, length: { minimum: 5}, format: { without: /\s/, message: "does not allow blank" }
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

  attribute :count_vote_up, :integer, default: 0
  attribute :count_vote_down, :integer, default: 0

  validates :link, presence: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :user, uniqueness: { scope: :movie }
  validates :value, inclusion: { in: [-1, 1] }

  after_save :update_movie_vote_count
  after_destroy :update_movie_vote_count

  def can_be_deleted_by?(user)
    user == self.user
  end

  private

  def update_movie_vote_count
    movie.update_vote_count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user

  def current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def authenticate_user!
    if not Current.user.present?
      flash[:danger] = "You need to sign in or sign up before continuing."
      redirect_to root_path
    end
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  include Pagy::Backend

  before_action :authenticate_user! , only: [:new, :create]

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if MoviesServices.create(@movie)
      flash[:success] = "Movie created successfully"
      redirect_to movies_path
    else
      # flash.now[:danger] = "Movie could not be created #{@movie.errors.full_messages}"
      render :new, status: :unprocessable_entity
    end
  end

  def index
    # TODO prefetch the votes
    @pagy, @movies = pagy(Movie.includes(:user).order(created_at: :desc))
  end

  private

  def movie_params
    params.require(:movie).permit(:link)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by(username: params[:username])

    if user.present? && user.authenticate(params[:password])
      flash[:success] = "You are signed in successfully"
      session[:user_id] = user.id
    end

    if user.present? && (not user.authenticate(params[:password]))
      flash[:danger] = "Invalid password"
    end

    if not user.present?
      # Create a new user
      @user = User.new(user_params)

      if @user.save
        session[:user_id] = @user.id
        flash[:success] = "User is created successfully"
      else
        flash[:danger] = helpers.build_error_message(@user.errors.full_messages)
      end
    end

    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def user_params
    params.permit(:username, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_vote, only: [:destroy]

  def create
    if VotesServices.vote(vote_params, current_user)
      @movie = Movie.find(vote_params[:movie_id])
      respond_to do |format|
        format.turbo_stream
        format.html do
          flash[:success] = "Vote created successfully"
          redirect_to movies_path
        end
      end
    else
      respond_to do
        format.html do
          flash.now[:danger] = "Vote could not be created"
          redirect_to movies_path, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    if @vote&.can_be_deleted_by?(current_user)
      @movie = @vote.movie
      if @vote.destroy
        respond_to do |format|
          format.turbo_stream
          format.html do
            flash[:success] = "Unvote successfully"
            redirect_to movies_path
          end
        end
      else
        respond_to do |format|
          format.html do
            flash.now[:danger] = "Unvote could not be performed"
            redirect_to movies_path, status: :unprocessable_entity
          end
        end
      end
    else
      respond_to do |format|
        format.html do
          flash.now[:danger] = "You can only unvote your own votes"
          redirect_to movies_path, status: :unprocessable_entity
        end
      end
    end
  end

  private

  def vote_params
    params.permit(:movie_id, :value)
  end

  def set_vote
    @vote = Vote.find_by(movie_id: params[:movie_id], user_id: current_user.id)
    puts @vote
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    Current.user
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  include Pagy::Frontend

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def build_error_message(messages)
    # Build error message
    error_message = "<p>Failed to create new user. There are some errors:</p><ul>"
    messages.each do |message|
      error_message << "<li>#{message}</li>"
    end
    error_message << "</ul>"
    error_message
  end
end

app/helpers/votes_helper.rb
module VotesHelper

  VOTE_UP_VALUE = 1
  VOTE_DOWN_VALUE = -1

  def user_vote?(movie)
    current_user.votes.where(movie_id: movie.id).exists?
  end

  def user_vote_up?(movie)
    current_user.votes.where(movie_id: movie.id, value: 1).exists?
  end

  def user_vote_down?(movie)
    current_user.votes.where(movie_id: movie.id, value: -1).exists?
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert"><%= value.html_safe %></div>
<% end %>

app/views/layouts/_login_form.html.erb
<%= form_with url: sign_in_path do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit "Login/Register" %>
<% end %>

app/views/layouts/_logout_form.html.erb
<div class="float-end">
  <span>Logged in as <%= current_user.username %></span>
  <%= link_to "Share a movie", new_movie_path, class: "btn btn-outline-primary" %>
  <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "btn btn-outline-danger" %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Funny Movies</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="ml-auto">
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <% if current_user %>
          <%= render 'layouts/logout_form' %>
        <% else %>
          <%= render 'layouts/login_form' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Funny Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <div class="container mt-3">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_movie.html.erb
<div class="card mb-3 movie-item" id="<%= "movie-item-#{dom_id(movie)}" %>">
  <div class="row g-0">
    <div class="col-md-4">
      <%= movie.embed_code&.html_safe %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <div class="row">
          <div class="col-10">
            <h5 class="card-title">
              <%= movie.title %>
            </h5>
            <p class="card-text">Shared by: <%= movie.user&.username %></p>
            <span>
              <%= movie.count_vote_up %>
              <i class="bi bi-hand-thumbs-up"></i>
            </span>
            <span>
              <%= movie.count_vote_down %>
              <i class="bi bi-hand-thumbs-down"></i>
            </span>
          </div>

          <%= render partial: "movies/vote", locals: { movie: movie } %>

        </div>
        <div class="row">
          <p>Description:</p>
          <p class="card-text"><%= movie.description %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/movies/_vote.html.erb
<% if current_user %>
  <% if not user_vote?(movie) %>
    <div class="col">
      <h1 class="card-title">
        <%= link_to '<i class="bi bi-hand-thumbs-up"></i>'.html_safe, votes_path(movie_id: movie.id, value: VotesHelper::VOTE_UP_VALUE), data: { "turbo-method": "post" } %>
      </h1>
    </div>
    <div class="col">
      <h1 class="card-title">
        <%= link_to '<i class="bi bi-hand-thumbs-down"></i>'.html_safe, votes_path(movie_id: movie.id, value: VotesHelper::VOTE_DOWN_VALUE), data: { "turbo-method": "post" } %>
      </h1>
    </div>
  <% else %>
    <% if user_vote_up?(movie) %>
      <div class="col">
        <h1 class="card-title">
          <%= link_to '<i class="bi bi-hand-thumbs-up-fill"></i>'.html_safe, votes_path(movie_id: movie.id), data: { "turbo-method": "delete" } %>
        </h1>
      </div>

    <% elsif user_vote_down?(movie) %>
      <div class="col">
        <h1 class="card-title">
          <%= link_to '<i class="bi bi-hand-thumbs-down-fill"></i>'.html_safe, votes_path(movie_id: movie.id), data: { "turbo-method": "delete" } %>
        </h1>
      </div>

    <% end %>
  <% end %>
<% end %>

app/views/movies/create.html.erb
<h1>movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<% if @movies.empty? %>
  <div class="alert alert-info">
    <p>There are no movies.</p>
  </div>
  </div>
<% else %>
  <% @movies.each do |movie| %>
    <%= render movie %>
  <% end %>

  <%== pagy_bootstrap_nav(@pagy) %>

<% end %>

app/views/movies/new.html.erb
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Share a YouTube video</h3>
  </div>
  <% if @movie.errors.any? %>
    <div style="color: red">
      <h2>There were some errors:</h2>
      <ul>
        <% @movie.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card-body">
    <%= form_with model: @movie do |f| %>
      <div class="mb-3 row">
        <%= f.label "YouTube URL", class: "col-sm-2 col-form-label" %>
        <div class="col-sm-10">
          <%= f.url_field :link, class: "form-control" %>
        </div>
      </div>

      <div class="mb-3">
        <%= f.submit "Share", class: "form-control btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/create.turbo_stream.erb
<%= turbo_stream.replace "movie-item-#{dom_id(@movie)}" do %>
  <%= render partial: "movies/movie", locals: { movie: @movie } %>
<% end %>

app/views/votes/destroy.html.erb
<h1>Votes#destroy</h1>
<p>Find me in app/views/votes/destroy.html.erb</p>

app/views/votes/destroy.turbo_stream.erb
<%= turbo_stream.replace "movie-item-#{dom_id(@movie)}" do %>
  <%= render partial: "movies/movie", locals: { movie: @movie } %>
<% end %>